### ISSUE TITLE
 ./configure -bash: ./configure: No such file or directory

### ISSUE THREAD

**Issue by mobsean** [mchehab/zbar#1]
Hello,

what am I missing? When I cd into the zbar folder to run
./configure 

I get:
 ./configure
-bash: ./configure: No such file or directory

Am I blind? or isn´t there any configure file in this repo?

greetz

**Comment by mchehab** [comment]
Actually, you need first to generate the configure file with autotools. The right way for doing it is to call:
    $ autoreconf -vfi && ./configure

I'll update INSTALL accordingly.

**Comment by mchehab** [comment]
This is just a test, in order to check if replying via e-mail to a github
thread works.

Please ignore it.
