### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by jasp00** [mchehab/zbar#11]
Before opening the pull request that adds continuous integration support, @mchehab, [Travis CI](https://travis-ci.org/) should be enabled for this repository. This way, the request should be automatically tested.

**Comment by mchehab** [comment]
Travis CI was enabled. I tried building stuff there, but it wants the config file:
`Build config file is required via repository settings, but config is empty. `

**Comment by mchehab** [comment]
I added a new target at zbar:
`make test`
That would be a perfect target to be run by Travis CI, as it would allow checking if are there any regressions at the parsers.
