### ISSUE TITLE
Dangerous code

### ISSUE THREAD

**Issue by shlyakpavel** [mchehab/zbar#110]
https://github.com/mchehab/zbar/blob/d2893738411be897a04caa42ffc13d1f6107d3c6/zbar/convert.c#L1162-L1167
Line 1166: vdo is checked against null pointer. However, previous lines dereference vdo. It would be great if someone more familiar with the code investigated that.

**Comment by mchehab** [comment]
both vdo and win will always be not NULL, as the code already prevents that.

See the first line of this function:

```
int zbar_negotiate_format (zbar_video_t *vdo,
                           zbar_window_t *win)
{
    static const uint32_t y800[2] = { fourcc('Y','8','0','0'), 0 };
    errinfo_t *errdst;
    const uint32_t *srcs, *dsts;
    unsigned min_cost = -1;
    uint32_t min_fmt = 0;
    const uint32_t *fmt;

    if(!vdo && !win)
        return(0);
...
    srcs = (vdo) ? vdo->formats : y800;
    dsts = (win) ? win->formats : y800;
```

Granted, we can remove the attempt to use Y8 fourcc.
