### ISSUE TITLE
code128: potential array overrun

### ISSUE THREAD

**Issue by shlyakpavel** [mchehab/zbar#111]
https://github.com/mchehab/zbar/blob/d2893738411be897a04caa42ffc13d1f6107d3c6/zbar/decoder/code128.c#L176
From static analyzer point of view, this code may cause an array overrun. I'm not sure if it's a false positive or not, but I decided to leave an issue as it's a potential security issue.

**Comment by mchehab** [comment]
It seems to be a false positive:

See:
```
#define NUM_CHARS 108           /* total number of character codes */
static const unsigned char characters[NUM_CHARS] = {
...
};

...
    switch(sig) {
    case 0x0014: idx = 0x0; break;
    case 0x0025: idx = 0x1; break;
    case 0x0034: idx = 0x2; break;
    case 0x0134: idx = 0x3; break;
    case 0x0143: idx = 0x4; break;
    case 0x0243: idx = 0x5; break;
    case 0x0341: idx = 0x6; break;
    case 0x0352: idx = 0x7; break;
    case 0x1024: idx = 0x8; break;
    case 0x1114: idx = 0x9; break;
    case 0x1134: idx = 0xa; break;
    case 0x1242: idx = 0xb; break;
    case 0x1243: idx = 0xc; break;
    case 0x1441: idx = 0xd; rev = 0; break;
    default: return(-1);
    }
    if(rev)
        idx += 0xe;
    c = characters[0x51 + idx];
```

The highest value that idx reaches is given by `idx = 0xc`, and `rev != 0`. On such case, we'll have `idx == 26` and `c = characters[107]`. which matches the biggest value of the array.

Looks good to me. It sounds that the static analyzer is not considering that, when `idx = 0x0d`, rev will be set to zero:
```
case 0x1441: idx = 0xd; rev = 0; break;
```
.
