### ISSUE TITLE
wrong assignment

### ISSUE THREAD

**Issue by maddin200** [mchehab/zbar#118]
r/test/test_decode.c:  line 1345

if (num_iter) {
        for (iter == 0; iter < num_iter; iter++) {  // <-- should be iter = 0
            test1();
            seed = (rand() << 8) ^ rand();
        }
    } else {
        test_databar_F_1();
        test_databar_F_3();
        test_orange();
        test1();
    }

**Comment by mchehab** [comment]
Thanks for the bug report!

Fixed.
