### ISSUE TITLE
Want to merge my modify?

### ISSUE THREAD

**Issue by ssrlive** [mchehab/zbar#131]
Hi @mchehab, 
I have get tons of modify to fit with C90 standard and VS 2010 in Windows.
Do you think it is necessary to merge into the master branch?

https://github.com/ShadowsocksR-Live/zbar

**Comment by wqh17101** [comment]
@ssrlive Yeah. we will merge it when we are free. Thank you! Maybe you can adjust your directories structure in the branch to merge for less aggressive modification like the VS properties file.
Also https://github.com/dani4/ZBarWin64/tree/master/zbar and https://github.com/NaturalHistoryMuseum/ZBarWin64 provide the windows support.  Also `libiconv`  is necessary for the Windows.
@mchehab

**Comment by ssrlive** [comment]
Hi @wqh17101 and @mchehab , please see #137 . The C code has committed.

**Comment by mchehab** [comment]
@wqh17101 could you please improve patch descriptions, and add a SoB, as described at:
   https://www.linuxtv.org/wiki/index.php/Development:_Submitting_Patches#Developer.27s_Certificate_of_Origin_1.1

When ready, please send us a Pull Request.

**Comment by wqh17101** [comment]
@ssrlive could you please improve patch descriptions, and add a SoB, as described at:
https://www.linuxtv.org/wiki/index.php/Development:_Submitting_Patches#Developer.27s_Certificate_of_Origin_1.1

When ready, please send us a Pull Request.

**Comment by ssrlive** [comment]
I don't know how to do it. Add the lines to the comment?

**Comment by ssrlive** [comment]
Done. It's OK? #137

**Comment by mchehab** [comment]
> I don't know how to do it. Add the lines to the comment?

Just add:

Signed-off-by: Your Name <your@email>

See, for instance:

https://github.com/mchehab/zbar/commit/ab66c2c8821357321df2c2326b1543f1f2a30325
