### ISSUE TITLE
zbar version should include patch version

### ISSUE THREAD

**Issue by wqh17101** [mchehab/zbar#143]
https://github.com/mchehab/zbar/blob/89e7900d85dd54ef351a7ed582aec6a5a5d7fa37/python/zbarmodule.c#L149-L152
this should be changed to 
```
    unsigned int major, minor, patch;
    zbar_version(&major, &minor, &patch);


    return(Py_BuildValue("III", major, minor, patch));
```

**Comment by mchehab** [comment]
Makes sense. Please submit this as a separate PR with just this patch, as this is unrelated with your ZBar-lite PR.
