### ISSUE TITLE
Support QR codes split in different images

### ISSUE THREAD

**Issue by jasp00** [mchehab/zbar#24]
This is Debian [#719013](https://bugs.debian.org/719013). Besides doing a graceful exit, I do not know whether QR codes split in different images should be supported. If the structured QR codes are in the same image, data is decoded successfully.

**Comment by mchehab** [comment]
> This is Debian [#719013](https://bugs.debian.org/719013). Besides doing a graceful exit, I do not know whether QR codes split in different images should be supported. If the structured QR codes are in the same image, data is decoded successfully.

Doing a graceful exit is something that it should do. Most (if not all) assert() calls the code should be replaced by proper return codes.

With regards to image join, I don't think that it should be a ZBar task to detect fragmented images and remount them into the right order it before parsing.
That sounds too much work for too little benefit. 

Also, one could fragment multiple barcodes into a set of image files that could be on a random order.  Depending on how barcodes are remounted, the code may be misinterpreted.
