### ISSUE TITLE
Typo in zbarimg/zbarimg.c

### ISSUE THREAD

**Issue by hosiet** [mchehab/zbar#29]
While working for the Debian package, I noticed the following typo:

https://github.com/mchehab/zbar/blob/dc9f5d1377ac82deab63cdadb0c86b7ecccc3098/zbarimg/zbarimg.c#L134

`shoud` should be `should`.

**Comment by mchehab** [comment]
> While working for the Debian package, I noticed the following typo:
> 
> [zbar/zbarimg/zbarimg.c](https://github.com/mchehab/zbar/blob/dc9f5d1377ac82deab63cdadb0c86b7ecccc3098/zbarimg/zbarimg.c#L134)
> 
> Line 134 in [dc9f5d1](/mchehab/zbar/commit/dc9f5d1377ac82deab63cdadb0c86b7ecccc3098)
>  "    Due to that, if you want, for example, ISBN-10, you shoud do:\n" 
> 
> `shoud` should be `should`.

Thanks for the report. Next time, feel free to submit a patch. I'm fixing it right now, together with a few other typos (using checkpatch.pl Kernel script, together with its typo dictionary).
