### ISSUE TITLE
Google Play services dependencies for Android porting

### ISSUE THREAD

**Issue by lewixlabs** [mchehab/zbar#37]
Hi,
maybe (probably) is an obvious question: Android port has a google play services dependencies, or not?
I ask this because, in my project, I use google vision.
Google Vision depends on google play service, which needs to be always updated, otherwise user, before scanning, has to wait until updating from google play store is completed.
It is a annoying issue

Thank you!
Lewix

**Comment by mchehab** [comment]
That's a good question. I dunno. To be frank, never tried to build ZBar for Android, but, if it has any dependency, feel free to send a patch removing it.
