### ISSUE TITLE
Decoding binary QR codes produces incorrect output

### ISSUE THREAD

**Issue by matheusmoreira** [mchehab/zbar#55]
Decoding QR codes containing binary data with `zbar 0.23` produces incorrect output.

I can reliably recover base64-encoded binary data encoded as alphanumeric and binary QR codes. However, binary data encoded directly in a binary QR code isn't decoded correctly by `zbar`.

Here's a script that reproduces the issue:

```bash
dd if=/dev/urandom bs=1024 count=1 > test.bin
base64 > test.b64                  < test.bin

qrencode -8 -o test.bin.8.png < test.bin
qrencode -8 -o test.b64.8.png < test.b64
qrencode -c -o test.b64.c.png < test.b64

zbarimg --raw test.bin.8.png | head -c -1 > test.bin.8.decoded.raw
zbarimg --raw test.b64.8.png | head -c -1 > test.b64.8.decoded.raw
zbarimg --raw test.b64.c.png | head -c -1 > test.b64.c.decoded.raw

sha1sum test.bin test.bin.8.decoded.raw \
        test.b64 test.b64.8.decoded.raw test.b64.c.decoded.raw

# 39378ba14d291710ac6458ced16fb0b29e901b84  test.bin
# 35138ed378bde1975e1908b3467dd8453b333bb4  test.bin.8.decoded.raw
# c4983f3be7f4a2ef3a63c9c9aa162155ffead6db  test.b64
# c4983f3be7f4a2ef3a63c9c9aa162155ffead6db  test.b64.8.decoded.raw
# c4983f3be7f4a2ef3a63c9c9aa162155ffead6db  test.b64.c.decoded.raw
```

I want to decode binary data that's been QR encoded and printed on paper. I verified that the problem exists when trying to decode scanned images as well as video captured with `zbarcam`.

**Comment by hifi** [comment]
For anyone stumbling across this from search engines, you need to add `-Sbinary` option for `zbarimg` to get the fixed behavior that was released back in [0.23.1](https://github.com/mchehab/zbar/releases/tag/0.23.1).

The man page was never updated to include that option so it's very easy to miss.

**Comment by matheusmoreira** [comment]
@hifi

That's true... I guess I forgot to update the manuals since I use the Arch Wiki so much. I edited the [paperkey] Arch Wiki article back in the day with instructions on how to use the binary decoding mode. It's the original use case I wanted this feature to enable. I also described the new options in the `--help` output and [answered a stackoverflow question][stackoverflow] about this.

Anyone want to make a pull request?

[paperkey]: https://wiki.archlinux.org/title/Paperkey
[stackoverflow]: https://stackoverflow.com/a/60518608/512904

**Comment by tim-tx** [comment]
I reran OP's commands, including `-Sbinary` for the binary decode, but still didn't recover the original.

```
dd if=/dev/urandom bs=1024 count=1 > test.bin
base64 > test.b64                  < test.bin

qrencode -8 -o test.bin.8.png < test.bin
qrencode -8 -o test.b64.8.png < test.b64
qrencode -c -o test.b64.c.png < test.b64

zbarimg --raw -Sbinary test.bin.8.png | head -c -1 > test.bin.8.decoded.raw
zbarimg --raw test.b64.8.png | head -c -1 > test.b64.8.decoded.raw
zbarimg --raw test.b64.c.png | head -c -1 > test.b64.c.decoded.raw

sha1sum test.bin test.bin.8.decoded.raw \
        test.b64 test.b64.8.decoded.raw test.b64.c.decoded.raw

# 8063b58230a5b7240d7011e733162ba98f59e068  test.bin
# cb30370cdc6b849a2afb90d78219b4abe15a686d  test.bin.8.decoded.raw
# 28c09caed811e064d99503920fb89e3e3aeb7686  test.b64
# 28c09caed811e064d99503920fb89e3e3aeb7686  test.b64.8.decoded.raw
# 28c09caed811e064d99503920fb89e3e3aeb7686  test.b64.c.decoded.raw
```

Am I missing something? ArchLinux `zbar 0.23.93-4`, `qrencode 4.1.1-3`

**Comment by matheusmoreira** [comment]
@tim-tx You also need `--oneshot`.

There might be an arbitrary number of QR codes in the image, so the tools will output separators between them in the form of a `\n` character. In my test script, I piped the output to `head -c -1` in order to remove that separator. I eventually added oneshot mode which prevents this separator from being written at all.

With `--raw --oneshot -Sqr.binary`, the output will be the exact binary contents of the first decoded QR code.

```bash
dd if=/dev/urandom bs=1024 count=1 > test.bin
base64 > test.b64                  < test.bin

qrencode -8 -o test.bin.8.png < test.bin
qrencode -8 -o test.b64.8.png < test.b64
qrencode -c -o test.b64.c.png < test.b64

zbarimg --raw --oneshot -Sqr.binary test.bin.8.png > test.bin.8.decoded.raw
zbarimg --raw test.b64.8.png | head -c -1 > test.b64.8.decoded.raw
zbarimg --raw test.b64.c.png | head -c -1 > test.b64.c.decoded.raw

sha1sum test.bin test.bin.8.decoded.raw \
        test.b64 test.b64.8.decoded.raw test.b64.c.decoded.raw

# cebbaa71a4753d27ae851781a27db6c8b95b9208  test.bin
# cebbaa71a4753d27ae851781a27db6c8b95b9208  test.bin.8.decoded.raw
# 9896a9adeb853c7f2c60afd2a89080e70d202cec  test.b64
# 9896a9adeb853c7f2c60afd2a89080e70d202cec  test.b64.8.decoded.raw
# 9896a9adeb853c7f2c60afd2a89080e70d202cec  test.b64.c.decoded.raw
```

**Comment by tim-tx** [comment]
Thanks @matheusmoreira seems like `head` or `--oneshot` takes care of the separator, but more importantly `-Sqr.binary` instead of `-Sbinary` gives the expected result. Maybe time to update Arch Wiki for paperkey again, which still says `-Sbinary`!

**Comment by matheusmoreira** [comment]
@tim-tx I tested `-Sbinary` as well and both gave the correct results. That form applies the `binary` option to all decoders, the `qr.` variant applies it to just the QR decoder which to my knowledge is the only one that makes use of it.

**Comment by tim-tx** [comment]
Ah, it was just `-Sbinary ... | head` that didn't work, though `-Sqr.binary ... | head` does work. `-Sbinary --oneshot` is good too. Thanks.
