### ISSUE TITLE
How To Start Zbar

### ISSUE THREAD

**Issue by KitchM** [mchehab/zbar#76]
Can anyone tell me how to start the application?  I have it installed on Debian 10 but there is no menu item.

Thanks.

**Comment by Ortega-Dan** [comment]
Hi, 

From a terminal do:
$ zbarimg 
![image](https://user-images.githubusercontent.com/24926168/73511290-2a883d00-43b3-11ea-8cf7-6c7e0e085fef.png)

Or you can also do zbarcam to run it from the default camera device.

Hope it helps

**Comment by KitchM** [comment]
Thank you.  I guess I thought something else.  Is there a GUI for it, or another that has one?

**Comment by matheusmoreira** [comment]
> Is there a GUI for it, or another that has one?

There's `zbarcam-gtk` and `zbarcam-qt`. These programs should be packaged by Debian as well.

**Comment by KitchM** [comment]
Thanks matheusmoreira.  I agree that it should be, but sadly it is not.  Couldn't find the .deb package anywhere else either.  Bummer.
