### ISSUE TITLE
Tons of Warnings in Xcode 11.4.1 when building the iPhone SDK project

### ISSUE THREAD

**Issue by ethanwa** [mchehab/zbar#88]
Any possibility you can fix these warnings and bring the iPhone version completely up-to-date?

It's so awesome that you have taken the time to fix the UIWebView deprecation already. I really appreciate it!

**Comment by mchehab** [comment]
Someone needs to provide us patches for that ;-)

I don't have iPhone - nor any Apple device here. Btw, if you could provide us a set of instructions to build ZBar for iPhone, I could setup Travis to do the builds, helping to avoid breakes on future ZBar patches.

**Comment by ethanwa** [comment]
Hi, I'm working through pay
