### ISSUE TITLE
Can't compile v0.23.1 due to missing gettext.h

### ISSUE THREAD

**Issue by paolostivanin** [mchehab/zbar#90]
```
zbarcam/zbarcam.c:38:10: fatal error: ../zbar/gettext.h: No such file or directory
   38 | #include "../zbar/gettext.h"
      |          ^~~~~~~~~~~~~~~~~~~
```

Config opts:
```
  - "--without-qt"
  - "--without-qt5"
  - "--without-gtk"
  - "--without-xv"
  - "--without-imagemagick"
  - "--without-dbus"
  - "--with-python=python3"
  - "--disable-doc"
  - "--enable-codes=qrcode"
```

v0.23 works fine though :+1:

**Comment by ffontaine** [comment]
It seems that official tarball (https://www.linuxtv.org/downloads/zbar/zbar-0.23.1.tar.bz2) does not contain zbar/gettext.h which have been added by commit d05911f8d5fb8c1e064bd93ed9ec9f038c5da096.

**Comment by mchehab** [comment]
This include is actually not needed, and got dropped on a133aea7880bbb56d75535e534716d0e16a3b61a. The next version's tarball should get this sorted out.
