### ISSUE TITLE
zbarcam changes line endings in binary mode on Windows

### ISSUE THREAD

**Issue by itsmattkc** [mchehab/zbar#97]
On Windows, using zbarcam to decode a QR code containing binary data will replace `0x0A` with `0x0D 0x0A` (obviously attempting to replacing Unix `\n` with Windows `\r\n`) despite `--raw` and `-Sbinary` being set. This is obviously undesirable for binary data and in most cases corrupts it.

I was able to fix this on my end by adding `_setmode(_fileno(stdout), _O_BINARY);` into `data_handler (zbar_image_t *img, const void *userdata)` in `zbarcam.c`:
```
        else if(format == RAW) {
            _setmode(_fileno(stdout), _O_BINARY);
            
            if(fwrite(zbar_symbol_get_data(sym),
                      zbar_symbol_get_data_length(sym),
                      1, stdout) != 1)
                continue;
        }
```
But I'm not sure if this is the best solution/place for it (or if it should be wrapped in a `_WIN32` ifdef?) so I haven't made a pull request. I'm happy to do so if anyone wishes though.

This issue does not affect zbarimg.

**Comment by mchehab** [comment]
Setting mode to O_BINARY is indeed the best way to fix it. Feel free to send such patch. It needs to be wrapped by a _WIN32 ifdef.
